# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Filter-RemoveEmpty
version:      0.02
version_from: lib/XML/Filter/RemoveEmpty.pm
installdirs:  site
requires:
    Alias:                         0
    enum:                          0
    Test::More:                    0
    Text::Trim:                    0
    XML::Filter::BufferText:       0
    XML::SAX::Base:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
